import Head from 'next/head'
import { useState, useEffect } from 'react'
import React from 'react'
import fetchWeather from './api/fetchWeather'

import fetchNews from './api/fetchNews'
import styles from "./index.module.scss"
import iconn from '../assets/icons/business-icon.svg'
import Image from 'next/image'
import BaseLayout from '../layouts/baselayout'
import { AppContext } from '../layouts/baselayout'
import { useContext } from 'react'
import AOS from 'aos';
import 'aos/dist/aos.css';

export default function Home() {

  const  appContext = useContext(AppContext);



  

  const dateObj = new Date();
  const [query, setQuery]= useState(appContext);
  const [weather, setWeather] = useState({status: 'd', results: []})
  const [news, setNews] = useState({status: 'd'})
  const [date, setDate] = useState(Date)
  const [icon, setIcon] = React.useState("")



  



  
  const getWeather = async (e) =>{
    
    const data = await fetchWeather('lagos');
    data.weather ? setWeather({...data},)  
    : setWeather({
        ...weather,
        error: "can't fetch weather infomation check network connection and city name"
      })
      
      
    
  }


  const getNews = async () =>{
    console.log('query', appContext)
   
      const data = await fetchNews('');
      
      data.status === 'OK' ? setNews({
          ...data
        })  : setNews({
          status: '',
          
          error: "can't fetch News check network connection"
        })


        
      
      
    
  }
  const path = "M12 7V3H2v18h20V7H12zM6 19H4v-2h2v2zm0-4H4v-2h2v2zm0-4H4V9h2v2zm0-4H4V5h2v2zm4 12H8v-2h2v2zm0-4H8v-2h2v2zm0-4H8V9h2v2zm0-4H8V5h2v2zm10 12h-8v-2h2v-2h-2v-2h2v-2h-2V9h8v10zm-2-8h-2v2h2v-2zm0 4h-2v2h2v-2z"

 

 
  useEffect(()=>{
    
    // weather.description ? setIcon(`https://openweathermap.org/img/wn/${weather.icon}@2x.png`) : setIcon("");
    AOS.init();
    getNews()
    getWeather()
    console.log('news',news)
    // console.log('weather', weather.results)
  },[weather.name])

  

  
  return (
    <BaseLayout>
      <div className={styles.index}>
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      
      
      
      
        {
          news.results? 
            <div className={styles.news_container} data-aos="fade-up">
              {news.results.map((article, index)=> {
                return (
                
                  <div className={styles.news_card  + ' animate__animated animate__bounceInUp'} key={index} style={{
                    color:'white'
                  }}>
                    <h3>{article.title}</h3>
                    <p>{article.abstract}</p>
                    <a href={article.url}>read more</a>
                  </div>
                )
              })}
            </div>
          :
          <div className={styles.news_container}>
            <p>{news.error? news.error : 'loading...'}</p>
          </div>
        }


      {
        weather.weather?

          <div className={styles.weatherCard}>
            <div className={styles.heading}>
              <p className={styles.city}>
                {weather.name}
                
              </p>

              <p className={styles.country}>{weather.sys.country}</p>
            </div>
            
            <div>
              <p className={styles.description}>
                {weather.weather[0].description}
              </p>
              <p className={styles.temp} >
                {Math.round(weather.main.temp)  }
                <sup> &deg;C</sup>
                
              </p>
            </div>
            
            
            

          
          </div>
        : <div className={styles.weatherCard}>
            <p>
              {weather.error? weather.error : 'loading...'}
            </p> 
          </div>
      }






      
      

      
      </div>

    
    
    </BaseLayout>

    
  )
}


{/* <label>Enter a city</label>
      <input type={"text"} className="search" 
        placeholder='search...'
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        onKeyPress={search}
      />


      <div className={styles.weatherCard}>
        
        <svg>{icon}</svg>
        <div>kk</div>
        <div><Image src={iconn} alt=''/></div>
        <img src={iconn}/>
        <svg width="24" height="24"  viewBox="0 0 24 24" focusable="false" className="icon"><path d={path}></path></svg>
        <div>
          <p className={styles.city}>
            {weather.name}
          </p>

          <p className={styles.country}>{weather.country}</p>
        </div>
        
        <p className={styles.date} style={{
          color: "black"
        }}>
          {date}
        </p>
        <p className={styles.temp} style={{
          display: weather.temp? "flex": "none",
          ...styles
          
        }} >
          {Math.round(weather.temp)  }
          <sup> &deg;C</sup>
          
        </p>

        
        <img src={iconn} alt=""/>

        
        <p className={styles.description}>
          {weather.description}
        </p>

        <p className={styles.error}>{weather.error}</p>
      
      </div> */}
